version: '3'

services:
    db:
        image: mysql
        container_name: easyappointments-database
        env_file:
            - variables.env
        volumes:
            - ./db:/var/lib/mysql
    
    app:
        build: .
        image: thelastbilly/easyapptcontained
        volumes: 
            - ./data:/easyappointments
            - ./certs:/certs
            - ./settings.csr:/settings.csr
        links:
            - db
        env_file:
            - variables.env
        ports:
            - 8000:443