version: '3'

volumes: 
    ea_db:
    ea_data:

services:
    db:
        restart: always
        image: mariadb
        env_file:
            - variables.env
        volumes:
            - ea_db:/var/lib/mysql
    
    app:
        restart: always
        #build: .
        image: thelastbilly/easyapptcontained
        volumes: 
            - ea_data:/easyappointments
            - ./certs:/certs
            - ./settings.csr:/settings.csr
        links:
            - db
        env_file:
            - variables.env
        ports:
            - 8000:443